import { useState, type FormEvent } from 'react';
import { useBootstrap } from '../../app/BootstrapProvider';
import { Button } from '../../components/ui/Button';
import { formatWeight } from '../../lib/format';
import { dateKey } from '../routine/selectors';

interface StoredExercise { id: string; name: string; sets?: number | string; reps?: number | string }
interface StoredWorkout { id: string; name: string; exercises: StoredExercise[] }
interface WorkoutEntry { workoutId: string; done: string[]; loads: Record<string, number> }
interface BodyEntry { id: string; date: string; weight: number | null; chest?: number | null; waist?: number | null }

export function TrainingScreen() {
  const { data, loading, error, saveStoreKey } = useBootstrap();
  const [selectedId, setSelectedId] = useState<string>('');
  if (loading) return <Message text="Carregando treinos…" />;
  if (error || !data) return <Message text="Não foi possível carregar os treinos." />;
  const workouts = Array.isArray(data.store.workouts) ? data.store.workouts as StoredWorkout[] : [];
  const log = data.store.workout_log && typeof data.store.workout_log === 'object' ? data.store.workout_log as Record<string, WorkoutEntry> : {};
  const body = Array.isArray(data.store.body_log) ? data.store.body_log as BodyEntry[] : [];
  const selected = workouts.find((w) => w.id === selectedId) ?? workouts[0];
  const key = dateKey(new Date());
  const entry = log[key]?.workoutId === selected?.id ? log[key] : { workoutId: selected?.id ?? '', done: [], loads: {} };
  const toggleExercise = async (id: string) => { const done = entry.done.includes(id) ? entry.done.filter((item) => item !== id) : [...entry.done, id]; await saveStoreKey('workout_log', { ...log, [key]: { ...entry, done } }); };
  const saveLoad = async (id: string, value: number) => { await saveStoreKey('workout_log', { ...log, [key]: { ...entry, loads: { ...entry.loads, [id]: value } } }); };
  const deleteWorkout = async () => { if (!selected) return; await saveStoreKey('workouts', workouts.filter((workout) => workout.id !== selected.id)); setSelectedId(''); };
  const addWorkout = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const workout: StoredWorkout = { id: crypto.randomUUID(), name: String(form.get('name')), exercises: [{ id: crypto.randomUUID(), name: String(form.get('exercise')), sets: Number(form.get('sets')), reps: Number(form.get('reps')) }] }; await saveStoreKey('workouts', [...workouts, workout]); event.currentTarget.reset(); };
  const addBody = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const record: BodyEntry = { id: crypto.randomUUID(), date: String(form.get('date')), weight: Number(form.get('weight')), waist: Number(form.get('waist')) || null }; await saveStoreKey('body_log', [...body, record]); event.currentTarget.reset(); };
  const deleteBody = (id: string) => saveStoreKey('body_log', body.filter((record) => record.id !== id));
  const currentWeight = [...body].reverse().find((item) => item.weight)?.weight ?? 0;
  const height = Number(data.store.body_height ?? 0);
  const bmi = height > 0 && currentWeight > 0 ? currentWeight / ((height / 100) ** 2) : 0;
  const monthStart = new Date(new Date().getFullYear(), new Date().getMonth(), 1);
  const monthDays = Array.from({ length: new Date(monthStart.getFullYear(), monthStart.getMonth() + 1, 0).getDate() }, (_, index) => new Date(monthStart.getFullYear(), monthStart.getMonth(), index + 1));
  const completedDays = new Set(Object.entries(log).filter(([, item]) => item.done?.length).map(([day]) => day));
  return <main className="mx-auto max-w-6xl px-4 pb-24 pt-24 sm:px-6"><header><p className="text-sm text-muted">Evolução e consistência</p><h1 className="mt-1 text-3xl font-semibold">Treinos</h1></header>
    <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_320px]"><section className="rounded-2xl border border-outline-variant bg-surface-container-low"><div className="border-b border-outline-variant p-5"><label className="text-sm text-muted">Treino de hoje<select value={selected?.id ?? ''} onChange={(e) => setSelectedId(e.target.value)} className="mt-2 block h-10 w-full rounded-lg border border-outline bg-surface-container px-3 text-on-surface">{workouts.map((workout) => <option key={workout.id} value={workout.id}>{workout.name}</option>)}</select></label></div><ul className="divide-y divide-outline-variant">{selected?.exercises?.length ? selected.exercises.map((exercise) => { const done = entry.done.includes(exercise.id); return <li key={exercise.id} className="flex items-center gap-4 p-5"><button onClick={() => void toggleExercise(exercise.id)} className={`h-5 w-5 rounded-md border ${done ? 'border-tertiary bg-tertiary' : 'border-outline'}`} aria-label={done ? 'Marcar exercício pendente' : 'Concluir exercício'} /><span className={`flex-1 ${done ? 'text-muted line-through' : ''}`}>{exercise.name}</span><span className="font-mono text-sm text-muted">{exercise.sets ?? '—'} × {exercise.reps ?? '—'}</span></li>; }) : <li className="p-8 text-center text-muted">Nenhum treino programado.</li>}</ul></section>
      <aside className="space-y-4"><div className="rounded-2xl border border-outline-variant bg-surface-container-low p-5"><p className="text-sm text-muted">Progresso do treino</p><p className="mt-2 font-mono text-4xl text-primary">{selected?.exercises?.length ? Math.round(entry.done.length / selected.exercises.length * 100) : 0}%</p>{selected && <Button variant="danger" size="sm" className="mt-4" onClick={() => void deleteWorkout()}>Excluir treino</Button>}</div><div className="rounded-2xl border border-outline-variant bg-surface-container-low p-5"><p className="text-sm text-muted">Peso atual</p><p className="mt-2 font-mono text-2xl">{formatWeight(currentWeight)}</p><p className="mt-2 text-xs text-muted">{body.length} registros corporais</p></div></aside></div>
    {selected && <section className="mt-6 rounded-2xl border border-outline-variant bg-surface-container-low p-5"><h2 className="font-semibold">Cargas de hoje</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{selected.exercises.map((exercise) => <label key={exercise.id} className="text-xs text-muted">{exercise.name}<input type="number" step="0.5" defaultValue={entry.loads[exercise.id] ?? ''} onBlur={(event) => void saveLoad(exercise.id, Number(event.currentTarget.value))} className="mt-1 h-10 w-full rounded-lg border border-outline bg-surface-container px-3" /></label>)}</div></section>}
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><form onSubmit={addWorkout} className="grid gap-3 rounded-2xl border border-outline-variant bg-surface-container-low p-5"><h2 className="font-semibold">Criar treino</h2><Field name="name" label="Nome do treino" /><Field name="exercise" label="Primeiro exercício" /><div className="grid grid-cols-2 gap-3"><Field name="sets" label="Séries" type="number" /><Field name="reps" label="Repetições" type="number" /></div><Button type="submit">Salvar treino</Button></form><form onSubmit={addBody} className="grid gap-3 rounded-2xl border border-outline-variant bg-surface-container-low p-5"><h2 className="font-semibold">Registrar medidas</h2><Field name="date" label="Data" type="date" defaultValue={dateKey(new Date())} /><Field name="weight" label="Peso (kg)" type="number" step="0.1" /><Field name="waist" label="Cintura (cm)" type="number" step="0.1" /><Button type="submit">Salvar registro</Button></form></div>
    <section className="mt-6 rounded-2xl border border-outline-variant bg-surface-container-low p-5"><h2 className="font-semibold">Histórico corporal</h2><ul className="mt-3 divide-y divide-outline-variant">{body.length ? body.slice().reverse().map((record) => <li key={record.id} className="flex items-center justify-between py-3"><span>{record.date}</span><span className="font-mono">{record.weight ? formatWeight(record.weight) : '—'}</span><button onClick={() => void deleteBody(record.id)} className="text-xs text-error">Excluir</button></li>) : <li className="py-6 text-center text-muted">Nenhuma medida registrada.</li>}</ul></section>
    <section className="mt-6 grid gap-4 rounded-2xl border border-outline-variant bg-surface-container-low p-5 sm:grid-cols-2"><div><h2 className="font-semibold">Altura e IMC</h2><p className="mt-2 text-sm text-muted">IMC atual: {bmi ? bmi.toFixed(1) : '—'}</p></div><label className="text-xs text-muted">Altura (cm)<input type="number" defaultValue={height || ''} onBlur={(event) => void saveStoreKey('body_height', Number(event.currentTarget.value))} className="mt-1 h-10 w-full rounded-lg border border-outline bg-surface-container px-3" /></label></section>
    <section className="mt-6 rounded-2xl border border-outline-variant bg-surface-container-low p-5"><div className="flex justify-between gap-3"><div><h2 className="font-semibold">Consistência mensal</h2><p className="mt-1 text-sm text-muted">Dias com pelo menos um exercício concluído.</p></div><strong className="font-mono text-primary">{monthDays.filter((day) => completedDays.has(dateKey(day))).length}</strong></div><div className="mt-4 grid grid-cols-7 gap-2">{monthDays.map((day) => <span key={dateKey(day)} title={day.toLocaleDateString('pt-BR')} className={`aspect-square rounded-sm border border-outline-variant ${completedDays.has(dateKey(day)) ? 'bg-tertiary' : 'bg-surface-container'}`} />)}</div></section>
  </main>;
}
function Field(props: { name: string; label: string; type?: string; step?: string; defaultValue?: string }) { return <label className="text-xs text-muted">{props.label}<input {...props} aria-label={props.label} required className="mt-1 h-10 w-full rounded-lg border border-outline bg-surface-container px-3 text-on-surface" /></label>; }
function Message({ text }: { text: string }) { return <main className="px-6 pt-28 text-muted">{text}</main>; }
