import { useEffect, useState, type FormEvent } from 'react';
import { useBootstrap } from '../../app/BootstrapProvider';
import { Button } from '../../components/ui/Button';
import { confirmTotp, disableTotp, enrollTotp, restoreBackup, updateEmailPreference, uploadAvatar } from '../../services/profile';
import { getSubscription, type Subscription } from '../../services/subscription';

export function ProfileScreen() {
  const { data, loading, error, demo, updateProfile } = useBootstrap();
  const [subscription, setSubscription] = useState<Subscription | null>(null);
  const [secret, setSecret] = useState(''); const [backupCodes, setBackupCodes] = useState<string[]>([]); const [message, setMessage] = useState('');
  useEffect(() => { if (!demo) getSubscription().then(setSubscription).catch(() => undefined); }, [demo]);
  if (loading) return <Message text="Carregando perfil…" />;
  if (error || !data) return <Message text="Não foi possível carregar o perfil." />;
  const { profile } = data;
  const changeNotifications = async () => { const value = !profile.notify_email; if (!demo) await updateEmailPreference(value); updateProfile({ notify_email: value }); };
  const changeAvatar = async (file?: File) => { if (!file) return; if (demo) return setMessage('Upload desativado no modo demonstração.'); const result = await uploadAvatar(file); updateProfile({ avatar: result.avatar }); setMessage('Avatar atualizado.'); };
  const startTotp = async () => { if (demo) return setMessage('TOTP exige uma sessão real.'); const result = await enrollTotp(); setSecret(result.secret); };
  const finishTotp = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const code = String(new FormData(event.currentTarget).get('code')); const result = await confirmTotp(code); setBackupCodes(result.backup_codes); updateProfile({ totp_enabled: true }); setSecret(''); };
  const stopTotp = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await disableTotp(String(new FormData(event.currentTarget).get('password'))); updateProfile({ totp_enabled: false }); };
  const importFile = async (file?: File) => { if (!file) return; await restoreBackup(file); setMessage('Backup restaurado. Recarregue para conferir os dados.'); };
  return <main className="mx-auto max-w-4xl px-4 pb-24 pt-24 sm:px-6"><header><p className="text-sm text-muted">Conta e segurança</p><h1 className="mt-1 text-3xl font-semibold">Perfil</h1></header>{message && <p role="status" className="mt-4 rounded-xl border border-primary/20 bg-primary/10 p-3 text-sm text-primary">{message}</p>}
    <div className="mt-8 divide-y divide-outline-variant rounded-2xl border border-outline-variant bg-surface-container-low"><section className="flex flex-wrap items-center gap-4 p-6">{profile.avatar ? <img src={`/${profile.avatar}`} alt="Avatar do usuário" className="h-14 w-14 rounded-full object-cover" /> : <div className="grid h-14 w-14 place-items-center rounded-full bg-primary text-lg font-semibold text-on-primary">{profile.username.slice(0, 2).toUpperCase()}</div>}<div className="flex-1"><h2 className="font-semibold">{profile.username}</h2><p className="text-sm text-muted">{profile.email}</p></div><label className="cursor-pointer rounded-lg border border-outline px-3 py-2 text-sm">Alterar avatar<input type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={(e) => void changeAvatar(e.target.files?.[0])} /></label></section>
      <Row title="Assinatura" value={subscription ? `${subscription.plan} · ${subscription.status}` : demo ? 'Demonstração' : 'Carregando…'} />
      <section className="flex items-center justify-between gap-4 p-6"><div><h2 className="font-medium">Notificações por e-mail</h2><p className="mt-1 text-sm text-muted">Receber alertas importantes do Orby.</p></div><button role="switch" aria-checked={profile.notify_email} onClick={() => void changeNotifications()} className={`h-7 w-12 rounded-full p-1 ${profile.notify_email ? 'bg-primary' : 'bg-surface-container-highest'}`}><span className={`block h-5 w-5 rounded-full bg-white transition-transform ${profile.notify_email ? 'translate-x-5' : ''}`} /></button></section>
      <section className="p-6"><h2 className="font-medium">Autenticação em duas etapas</h2><p className="mt-1 text-sm text-muted">Status: {profile.totp_enabled ? 'ativada' : 'desativada'}.</p>{!profile.totp_enabled && !secret && <Button className="mt-4" onClick={() => void startTotp()}>Configurar TOTP</Button>}{secret && <form onSubmit={finishTotp} className="mt-4 grid gap-3"><p className="break-all rounded-lg bg-surface-container p-3 font-mono text-sm">Segredo: {secret}</p><input name="code" inputMode="numeric" required aria-label="Código TOTP" placeholder="Código de 6 dígitos" className="h-10 rounded-lg border border-outline bg-surface-container px-3" /><Button type="submit">Confirmar</Button></form>}{profile.totp_enabled && <form onSubmit={stopTotp} className="mt-4 flex gap-3"><input name="password" type="password" required aria-label="Senha para desativar TOTP" placeholder="Sua senha" className="h-10 flex-1 rounded-lg border border-outline bg-surface-container px-3" /><Button type="submit" variant="danger">Desativar</Button></form>}{backupCodes.length > 0 && <div className="mt-4 rounded-lg border border-warning/30 p-3"><p className="text-sm text-warning">Guarde estes códigos uma única vez:</p><code className="mt-2 block whitespace-pre-wrap">{backupCodes.join('\n')}</code></div>}</section>
      <section className="flex flex-wrap gap-3 p-6"><a href="/api/export.php" className="rounded-lg border border-outline px-4 py-2 text-sm">Exportar backup</a><label className="cursor-pointer rounded-lg border border-outline px-4 py-2 text-sm">Importar backup<input type="file" accept="application/json,.json" className="sr-only" onChange={(e) => void importFile(e.target.files?.[0])} /></label><a href="/logout.php" className="rounded-lg border border-error/30 px-4 py-2 text-sm text-error">Sair</a></section></div>
  </main>;
}
function Row({ title, value }: { title: string; value: string }) { return <section className="flex items-center justify-between gap-4 p-6"><div><h2 className="font-medium">{title}</h2><p className="mt-1 text-sm text-muted">Informação da sua conta.</p></div><span className="text-sm text-on-surface-variant">{value}</span></section>; }
function Message({ text }: { text: string }) { return <main className="px-6 pt-28 text-muted">{text}</main>; }
