import { useState, type FormEvent } from 'react';
import { useBootstrap } from '../../app/BootstrapProvider';
import { Button } from '../../components/ui/Button';
import { formatCurrency } from '../../lib/format';
import { previewOfx, type OfxRow } from '../../services/finance';
import type { AccountV2, IncomeLine } from './contracts';
import { financeSummary, isCard } from './selectors';
import { ApiError } from '../../services/api-client';

const tabs = ['Visão financeira', 'Contas e cartões', 'Extrato', 'Rendas', 'Orçamento', 'Cofrinhos', 'Relatórios'] as const;
export function FinanceScreen({ onNewExpense }: { onNewExpense: () => void }) {
  const { data, loading, error, replaceFinanceSet, saveStoreKey } = useBootstrap();
  const [tab, setTab] = useState<(typeof tabs)[number]>(tabs[0]);
  const [ofxRows, setOfxRows] = useState<OfxRow[]>([]);
  const [actionError, setActionError] = useState('');
  if (loading) return <Message text="Carregando financeiro…" />;
  if (error || !data) return <Message text="Não foi possível carregar o financeiro." />;
  const summary = financeSummary(data.finance);
  const addAccount = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const account: AccountV2 = { id: crypto.randomUUID(), label: String(form.get('label')), tipo: String(form.get('tipo')), saldo: Number(form.get('saldo')), chequeEspecial: 0, limite: Number(form.get('limite')), fatura: 0, fechamento: null, vencimento: null, bank: String(form.get('bank')) || null, principal: false, createdAt: Date.now() }; await replaceFinanceSet('accounts_v2', [...data.finance.accounts_v2, account]); event.currentTarget.reset(); };
  const addIncome = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const income: IncomeLine = { id: crypto.randomUUID(), label: String(form.get('label')), value: Number(form.get('value')), type: 'fixa', endDate: null, payday: null, accountId: null, createdAt: Date.now() }; await replaceFinanceSet('income_lines', [...data.finance.income_lines, income]); event.currentTarget.reset(); };
  const remove = (key: 'accounts_v2' | 'income_lines' | 'expense_lines_v4', id: string) => replaceFinanceSet(key, (data.finance[key] as { id: string }[]).filter((item) => item.id !== id));
  const loadOfx = async (file?: File) => { if (!file) return; setActionError(''); try { setOfxRows((await previewOfx(file)).rows); } catch (error) { setActionError(error instanceof ApiError && error.status === 402 ? 'A importação OFX exige o plano Individual. Seu arquivo não foi descartado da seleção.' : 'Não foi possível analisar o arquivo OFX.'); } };
  const importOfxRows = async () => { const additions = ofxRows.filter((row) => !row.dup).map((row) => ({ id: row.fitid || crypto.randomUUID(), label: row.desc, value: Math.abs(row.value), date: row.date, time: null, recorrencia: 'none' as const, categoria: null, method: null, bank: null, accountId: null, parcelas: 1, createdAt: Date.now() })); await replaceFinanceSet('expense_lines_v4', [...data.finance.expense_lines_v4, ...additions]); setOfxRows([]); };
  const addVault = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); await saveStoreKey('vaults', [...data.finance.vaults, { id: crypto.randomUUID(), accountId: String(form.get('accountId')), name: String(form.get('name')), goal: Number(form.get('goal')), saved: 0, createdAt: Date.now() }]); event.currentTarget.reset(); };
  const saveBudget = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const goals = data.store.budget_goals && typeof data.store.budget_goals === 'object' ? data.store.budget_goals as Record<string, number> : {}; await saveStoreKey('budget_goals', { ...goals, [String(form.get('category'))]: Number(form.get('value')) }); event.currentTarget.reset(); };
  const transfer = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const fromId = String(form.get('fromId')), toId = String(form.get('toId')), value = Number(form.get('value')); if (!fromId || !toId || fromId === toId || value <= 0) return; const accounts = data.finance.accounts_v2.map((account) => ({ ...account })); const from = accounts.find((a) => a.id === fromId), to = accounts.find((a) => a.id === toId); if (!from || !to) return; from.saldo -= value; const card = isCard(to); if (card) to.fatura = Math.max(0, to.fatura - value); else to.saldo += value; const transfers = [...data.finance.transfers, { id: crypto.randomUUID(), fromId, toId, value, date: new Date().toISOString().slice(0, 10), kind: card ? 'payment' : 'transfer', createdAt: Date.now() }]; await replaceFinanceSet('accounts_v2', accounts); try { await saveStoreKey('transfers', transfers); } catch (error) { await replaceFinanceSet('accounts_v2', data.finance.accounts_v2); throw error; } event.currentTarget.reset(); };
  return <main className="mx-auto max-w-[1200px] px-4 pb-24 pt-24 sm:px-6">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-muted">Controle e planejamento</p><h1 className="mt-1 text-3xl font-semibold">Financeiro</h1></div><Button onClick={onNewExpense}>Lançar despesa</Button></header>
    <div className="mt-7 flex gap-1 overflow-x-auto border-b border-outline-variant" role="tablist">{tabs.map((item) => <button key={item} role="tab" aria-selected={tab === item} onClick={() => setTab(item)} className={`shrink-0 border-b-2 px-3 py-3 text-sm ${tab === item ? 'border-primary text-primary' : 'border-transparent text-muted'}`}>{item}</button>)}</div>
    <section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Patrimônio', summary.netWorth], ['Saldo total', summary.totalBalance], ['Fatura', summary.totalInvoice], ['Crédito disponível', summary.availableCredit]].map(([label, value]) => <div key={String(label)} className="rounded-2xl border border-outline-variant bg-surface-container-low p-5"><p className="text-sm text-muted">{label}</p><p className="mt-2 font-mono text-xl">{formatCurrency(Number(value))}</p></div>)}</section>
    {actionError && <p role="alert" className="mt-5 rounded-xl border border-warning/30 bg-warning/10 p-4 text-sm text-warning">{actionError}</p>}
    <section className="mt-6 rounded-2xl border border-outline-variant bg-surface-container-low p-5"><h2 className="font-semibold">{tab}</h2>
      {tab === 'Contas e cartões' && <><FinanceList rows={data.finance.accounts_v2.map((a) => ({ id: a.id, title: a.label, detail: `${a.bank ?? 'Sem banco'} · ${a.tipo}`, value: isCard(a) ? a.fatura : a.saldo }))} onDelete={(id) => void remove('accounts_v2', id)} /><SimpleForm onSubmit={addAccount} fields={[['label','Nome'],['bank','Banco'],['saldo','Saldo','number'],['limite','Limite','number']]} select /></>}
      {tab === 'Extrato' && <><FinanceList rows={data.finance.expense_lines_v4.map((e) => ({ id: e.id, title: e.label, detail: e.date ?? 'Sem data', value: -e.value }))} onDelete={(id) => void remove('expense_lines_v4', id)} /><label className="mt-5 block text-sm text-muted">Importar OFX (prévia)<input type="file" accept=".ofx" onChange={(e) => void loadOfx(e.target.files?.[0])} className="mt-2 block" /></label>{ofxRows.length > 0 && <div className="mt-3 flex items-center gap-3"><p className="text-sm text-primary">{ofxRows.length} lançamentos encontrados.</p><Button size="sm" onClick={() => void importOfxRows()}>Importar não duplicados</Button></div>}</>}
      {tab === 'Rendas' && <><FinanceList rows={data.finance.income_lines.map((i) => ({ id: i.id, title: i.label, detail: i.type ?? 'renda', value: i.value }))} onDelete={(id) => void remove('income_lines', id)} /><SimpleForm onSubmit={addIncome} fields={[['label','Descrição'],['value','Valor','number']]} /></>}
      {tab === 'Cofrinhos' && <><FinanceList rows={data.finance.vaults.map((v) => ({ id: v.id, title: v.label ?? v.name ?? 'Cofrinho', detail: 'Reserva', value: v.saldo ?? v.saved ?? 0 }))} /><form onSubmit={addVault} className="mt-5 grid gap-3 border-t border-outline-variant pt-5 sm:grid-cols-2"><Field name="name" label="Nome" /><Field name="goal" label="Meta" type="number" /><AccountSelect name="accountId" accounts={data.finance.accounts_v2.filter((a) => !isCard(a))} /><Button type="submit">Criar cofrinho</Button></form></>}
      {tab === 'Visão financeira' && <><p className="mt-4 text-sm text-on-surface-variant">Resumo consolidado das suas contas, cartões, rendas e despesas.</p><form onSubmit={transfer} className="mt-5 grid gap-3 border-t border-outline-variant pt-5 sm:grid-cols-2"><AccountSelect name="fromId" label="Origem" accounts={data.finance.accounts_v2.filter((a) => !isCard(a))} /><AccountSelect name="toId" label="Destino ou cartão" accounts={data.finance.accounts_v2} /><Field name="value" label="Valor" type="number" /><Button type="submit">Transferir ou pagar fatura</Button></form></>}
      {tab === 'Orçamento' && <form onSubmit={saveBudget} className="mt-5 grid gap-3 sm:grid-cols-2"><Field name="category" label="Categoria" /><Field name="value" label="Limite mensal" type="number" /><Button type="submit">Salvar limite</Button></form>}
      {tab === 'Relatórios' && <div className="mt-4 flex flex-wrap gap-3"><a href="/api/export.php" className="rounded-lg border border-outline px-4 py-2 text-sm">Exportar dados</a><p className="self-center text-sm text-muted">Use o backup JSON para o relatório anual e declaração.</p></div>}
    </section>
  </main>;
}
function FinanceList({ rows, onDelete }: { rows: { id: string; title: string; detail: string; value: number }[]; onDelete?: (id: string) => void }) { return <ul className="mt-4 divide-y divide-outline-variant">{rows.length ? rows.map((row) => <li key={row.id} className="flex items-center justify-between gap-4 py-4"><div><p>{row.title}</p><p className="text-xs text-muted">{row.detail}</p></div><div className="flex items-center gap-3"><span className="font-mono">{formatCurrency(row.value)}</span>{onDelete && <button onClick={() => onDelete(row.id)} className="text-xs text-error">Excluir</button>}</div></li>) : <li className="py-8 text-center text-muted">Nenhum registro.</li>}</ul>; }
function SimpleForm({ onSubmit, fields, select }: { onSubmit: (event: FormEvent<HTMLFormElement>) => void; fields: [string,string,string?][]; select?: boolean }) { return <form onSubmit={onSubmit} className="mt-5 grid gap-3 border-t border-outline-variant pt-5 sm:grid-cols-2">{fields.map(([name,label,type]) => <label key={name} className="text-xs text-muted">{label}<input name={name} type={type ?? 'text'} required className="mt-1 h-10 w-full rounded-lg border border-outline bg-surface-container px-3 text-on-surface" /></label>)}{select && <label className="text-xs text-muted">Tipo<select name="tipo" className="mt-1 h-10 w-full rounded-lg border border-outline bg-surface-container px-3"><option value="conta">Conta</option><option value="poupanca">Poupança</option><option value="cartao">Cartão</option></select></label>}<Button type="submit">Adicionar</Button></form>; }
function Field({ name, label, type = 'text' }: { name: string; label: string; type?: string }) { return <label className="text-xs text-muted">{label}<input name={name} type={type} step={type === 'number' ? '0.01' : undefined} required className="mt-1 h-10 w-full rounded-lg border border-outline bg-surface-container px-3 text-on-surface" /></label>; }
function AccountSelect({ name, accounts, label = 'Conta' }: { name: string; accounts: AccountV2[]; label?: string }) { return <label className="text-xs text-muted">{label}<select name={name} required className="mt-1 h-10 w-full rounded-lg border border-outline bg-surface-container px-3">{accounts.map((account) => <option key={account.id} value={account.id}>{account.label}</option>)}</select></label>; }
function Message({ text }: { text: string }) { return <main className="px-6 pt-28 text-muted">{text}</main>; }
