import { useState, type FormEvent } from 'react';
import { useBootstrap } from '../../app/BootstrapProvider';
import { Button } from '../../components/ui/Button';
import { Modal } from '../../components/ui/Modal';
import type { Task } from '../routine/contracts';
import { occurrenceId, routineSummary, tasksOnDate } from '../routine/selectors';

export function AgendaScreen({ onNewTask }: { onNewTask: () => void }) {
  const { data, loading, error, toggleTask, deleteTask, updateTask } = useBootstrap();
  const [date, setDate] = useState(new Date());
  const [view, setView] = useState<'day' | 'week' | 'month' | 'year'>('day');
  const [pending, setPending] = useState<string | null>(null);
  const [editing, setEditing] = useState<Task | null>(null);
  if (loading) return <PageMessage text="Carregando agenda…" />;
  if (error || !data) return <PageMessage text="Não foi possível carregar a agenda." />;
  const tasks = tasksOnDate(data.tasks, date);
  const rangeDates = datesForView(date, view);
  const occurrences = rangeDates.flatMap((occurrenceDate) => tasksOnDate(data.tasks, occurrenceDate).map((task) => ({ task, date: occurrenceDate })));
  const last30 = Array.from({ length: 30 }, (_, index) => new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate() - 29 + index));
  const completionDays = last30.map((day) => { const scheduled = tasksOnDate(data.tasks, day); const completed = scheduled.filter((task) => data.checklist[occurrenceId(task, day)]).length; return { day, total: scheduled.length, completed, rate: scheduled.length ? Math.round(completed / scheduled.length * 100) : 0 }; });
  const totals30 = completionDays.reduce((sum, item) => ({ total: sum.total + item.total, completed: sum.completed + item.completed }), { total: 0, completed: 0 });
  const categoryRates = [...new Set(data.tasks.map((task) => task.cat))].map((category) => { const items = last30.flatMap((day) => tasksOnDate(data.tasks.filter((task) => task.cat === category), day).map((task) => ({ task, day }))); const completed = items.filter(({ task, day }) => data.checklist[occurrenceId(task, day)]).length; return { category, rate: items.length ? Math.round(completed / items.length * 100) : 0 }; });
  const summary = routineSummary(data.tasks, data.checklist, date);
  const move = (days: number) => setDate((current) => new Date(current.getFullYear(), current.getMonth(), current.getDate() + days));
  const run = async (id: string, action: () => Promise<void>) => { setPending(id); try { await action(); } finally { setPending(null); } };
  const saveEdit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!editing) return; const form = new FormData(event.currentTarget); await updateTask({ ...editing, title: String(form.get('title')), date: String(form.get('date')), time: String(form.get('time')), cat: String(form.get('cat')), duration: Number(form.get('duration')) }); setEditing(null); };

  return <main className="mx-auto max-w-6xl px-4 pb-24 pt-24 sm:px-6">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-muted">Organize seu tempo</p><h1 className="mt-1 text-3xl font-semibold text-on-surface">Agenda</h1></div><Button onClick={onNewTask}>Nova tarefa</Button></header>
    <div className="mt-8 flex flex-wrap items-center justify-between gap-3 border-b border-outline-variant pb-4"><div className="flex gap-2"><button className="rounded-lg border border-outline px-3 py-2" onClick={() => move(view === 'day' ? -1 : view === 'week' ? -7 : -30)}>Anterior</button><button className="rounded-lg border border-outline px-3 py-2" onClick={() => setDate(new Date())}>Hoje</button><button className="rounded-lg border border-outline px-3 py-2" onClick={() => move(view === 'day' ? 1 : view === 'week' ? 7 : 30)}>Próximo</button></div><p className="text-on-surface-variant">{date.toLocaleDateString('pt-BR', { dateStyle: 'full' })}</p></div>
    <div className="mt-4 flex gap-2" role="tablist" aria-label="Visualização da agenda">{(['day','week','month','year'] as const).map((item) => <button key={item} role="tab" aria-selected={view === item} onClick={() => setView(item)} className={`rounded-lg px-3 py-2 text-sm ${view === item ? 'bg-primary text-on-primary' : 'border border-outline text-muted'}`}>{item === 'day' ? 'Dia' : item === 'week' ? 'Semana' : item === 'month' ? 'Mês' : 'Ano'}</button>)}</div>
    {view !== 'day' && <section className="mt-6 rounded-2xl border border-outline-variant bg-surface-container-low p-5"><h2 className="font-semibold">Compromissos no período</h2><ul className="mt-3 max-h-80 divide-y divide-outline-variant overflow-y-auto">{occurrences.length ? occurrences.map(({ task, date: occurrenceDate }) => <li key={`${task.id}:${occurrenceDate.toISOString()}`} className="flex gap-4 py-3"><time className="w-28 text-sm text-muted">{occurrenceDate.toLocaleDateString('pt-BR')} · {task.time}</time><span>{task.title}</span></li>) : <li className="py-6 text-center text-muted">Nenhuma tarefa no período.</li>}</ul></section>}
    <section className="mt-6 grid gap-6 lg:grid-cols-[1fr_280px]">
      <div><h2 className="text-lg font-semibold">Tarefas da data</h2><ul className="mt-3 divide-y divide-outline-variant rounded-2xl border border-outline-variant bg-surface-container-low">
        {tasks.length ? tasks.map((task) => { const done = Boolean(data.checklist[occurrenceId(task, date)]); return <li key={task.id} className="flex min-h-16 items-center gap-4 px-5"><button disabled={pending === task.id} onClick={() => void run(task.id, () => toggleTask(task, date))} className={`h-5 w-5 rounded-md border ${done ? 'border-tertiary bg-tertiary' : 'border-outline'}`} aria-label={done ? 'Marcar como pendente' : 'Marcar como concluída'} /><time className="font-mono text-sm text-muted">{task.time}</time><div className="min-w-0 flex-1"><p className={done ? 'text-muted line-through' : 'text-on-surface'}>{task.title}</p><p className="text-xs text-muted">{task.cat} · {task.duration} min</p></div><button onClick={() => setEditing(task)} className="rounded-lg px-2 py-2 text-sm text-primary">Editar</button><button disabled={pending === task.id} onClick={() => void run(task.id, () => deleteTask(task.id))} className="rounded-lg px-2 py-2 text-sm text-error hover:bg-error/10" aria-label={`Excluir ${task.title}`}>Excluir</button></li>; }) : <li className="p-8 text-center text-on-surface-variant">Nenhuma tarefa nesta data.</li>}
      </ul></div>
      <aside className="rounded-2xl border border-outline-variant bg-surface-container-low p-5"><h2 className="font-semibold">Resumo do dia</h2><p className="mt-5 font-mono text-4xl text-primary">{summary.progress}%</p><p className="mt-2 text-sm text-muted">{summary.completed} de {summary.total} concluídas</p><div className="mt-6 border-t border-outline-variant pt-4"><p className="text-sm text-on-surface-variant">Visualizações</p><p className="mt-2 text-sm text-muted">Dia · Semana · Mês · Ano</p></div></aside>
    </section>
    <section className="mt-6 rounded-2xl border border-outline-variant bg-surface-container-low p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-semibold">Últimos 30 dias</h2><p className="mt-1 text-sm text-muted">Taxa de conclusão e consistência diária.</p></div><p className="font-mono text-2xl text-primary">{totals30.total ? Math.round(totals30.completed / totals30.total * 100) : 0}%</p></div><div className="mt-5 grid grid-cols-10 gap-2 sm:grid-cols-15" aria-label="Heatmap de conclusão dos últimos 30 dias">{completionDays.map((item) => <span key={item.day.toISOString()} title={`${item.day.toLocaleDateString('pt-BR')}: ${item.rate}%`} className="aspect-square rounded-sm border border-outline-variant" style={{ backgroundColor: `color-mix(in srgb, var(--color-primary) ${Math.max(5, item.rate)}%, transparent)` }} />)}</div></section>
    <Modal isOpen={Boolean(editing)} onClose={() => setEditing(null)} title="Editar tarefa">{editing && <form onSubmit={saveEdit} className="grid gap-3"><EditField name="title" label="Título" defaultValue={editing.title} /><div className="grid grid-cols-2 gap-3"><EditField name="date" label="Data" type="date" defaultValue={editing.date} /><EditField name="time" label="Horário" type="time" defaultValue={editing.time} /></div><div className="grid grid-cols-2 gap-3"><EditField name="cat" label="Categoria" defaultValue={editing.cat} /><EditField name="duration" label="Duração" type="number" defaultValue={String(editing.duration)} /></div><Button type="submit">Salvar alterações</Button></form>}</Modal>
    <section className="mt-6 rounded-2xl border border-outline-variant bg-surface-container-low p-5"><h2 className="font-semibold">Conclusão por categoria</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{categoryRates.length ? categoryRates.map((item) => <div key={item.category}><div className="flex justify-between text-sm"><span>{item.category}</span><span className="font-mono">{item.rate}%</span></div><div className="mt-2 h-2 rounded-full bg-surface-container-highest"><div className="h-full rounded-full bg-primary" style={{ width: `${item.rate}%` }} /></div></div>) : <p className="text-sm text-muted">Sem categorias no período.</p>}</div></section>
  </main>;
}

function PageMessage({ text }: { text: string }) { return <main className="px-6 pt-28 text-on-surface-variant">{text}</main>; }
function EditField({ name, label, type = 'text', defaultValue }: { name: string; label: string; type?: string; defaultValue: string }) { return <label className="text-xs text-muted">{label}<input name={name} type={type} defaultValue={defaultValue} required className="mt-1 h-10 w-full rounded-lg border border-outline bg-surface-container px-3" /></label>; }
function datesForView(anchor: Date, view: 'day' | 'week' | 'month' | 'year') { if (view === 'day') return [anchor]; let start: Date; let count: number; if (view === 'week') { start = new Date(anchor.getFullYear(), anchor.getMonth(), anchor.getDate() - anchor.getDay()); count = 7; } else if (view === 'month') { start = new Date(anchor.getFullYear(), anchor.getMonth(), 1); count = new Date(anchor.getFullYear(), anchor.getMonth() + 1, 0).getDate(); } else { start = new Date(anchor.getFullYear(), 0, 1); count = Math.round((new Date(anchor.getFullYear() + 1, 0, 1).getTime() - start.getTime()) / 86_400_000); } return Array.from({ length: count }, (_, index) => new Date(start.getFullYear(), start.getMonth(), start.getDate() + index)); }
