import {
  Activity,
  ArrowDown,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  Banknote,
  BadgeDollarSign,
  Bell,
  CalendarCheck,
  CalendarDays,
  CalendarRange,
  ChartNoAxesCombined,
  ChartPie,
  ChartSpline,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleCheck,
  CircleHelp,
  CirclePlus,
  CloudCheck,
  CloudOff,
  CreditCard,
  Download,
  Dumbbell,
  FileUp,
  Flame,
  FlaskConical,
  Gem,
  HandCoins,
  Hourglass,
  KeyRound,
  Landmark,
  Laptop,
  LayoutDashboard,
  ListChecks,
  LockKeyhole,
  LogOut,
  Medal,
  Moon,
  Palette,
  Paperclip,
  Pencil,
  PiggyBank,
  Printer,
  Plus,
  ReceiptText,
  Rocket,
  Search,
  SearchX,
  ShieldCheck,
  Star,
  Sun,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Target,
  Upload,
  User,
  UserCog,
  UtensilsCrossed,
  Wallet,
  WalletCards,
  Weight,
  X,
  type LucideIcon,
} from "lucide-react"
import { cn } from "../lib/cn"

interface IconProps {
  name: string
  filled?: boolean
  className?: string
}

const ICONS: Record<string, LucideIcon> = {
  account_balance: Landmark,
  account_balance_wallet: WalletCards,
  add: Plus,
  add_chart: ChartNoAxesCombined,
  add_circle: CirclePlus,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  attach_file: Paperclip,
  check: Check,
  check_circle: CircleCheck,
  checklist: ListChecks,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  cloud_done: CloudCheck,
  cloud_off: CloudOff,
  credit_card: CreditCard,
  credit_score: BadgeDollarSign,
  dark_mode: Moon,
  calendar_month: CalendarDays,
  date_range: CalendarRange,
  delete: Trash2,
  devices: Laptop,
  donut_large: ChartPie,
  edit: Pencil,
  event: CalendarDays,
  event_available: CalendarCheck,
  exercise: Dumbbell,
  expand_more: ChevronDown,
  finance: ChartNoAxesCombined,
  fitness_center: Dumbbell,
  grid_view: LayoutDashboard,
  hourglass_top: Hourglass,
  insights: ChartSpline,
  light_mode: Sun,
  local_fire_department: Flame,
  logout: LogOut,
  manage_accounts: UserCog,
  military_tech: Medal,
  monitor_heart: Activity,
  monitor_weight: Weight,
  north_east: TrendingUp,
  notifications: Bell,
  palette: Palette,
  password: KeyRound,
  payments: HandCoins,
  paid: Banknote,
  person: User,
  print: Printer,
  radio_button_unchecked: Circle,
  restaurant: UtensilsCrossed,
  receipt_long: ReceiptText,
  rocket_launch: Rocket,
  savings: PiggyBank,
  science: FlaskConical,
  search: Search,
  search_off: SearchX,
  shield: ShieldCheck,
  south_east: TrendingDown,
  sports_gymnastics: Dumbbell,
  ssid_chart: ChartSpline,
  star: Star,
  star_outline: Star,
  stars: Star,
  swap_horiz: ArrowLeftRight,
  task_alt: ListChecks,
  trending_down: TrendingDown,
  trending_up: TrendingUp,
  upload: Upload,
  upload_file: FileUp,
  wallet: Wallet,
  workspace_premium: Trophy,
  trophy: Trophy,
  lock: LockKeyhole,
  target: Target,
  verified: ShieldCheck,
  diamond: Gem,
}

/** Compatibilidade com os nomes legados, renderizando SVG Lucide leve. */
export function Icon({ name, filled = false, className }: IconProps) {
  const Component = ICONS[name] ?? CircleHelp
  return (
    <Component
      aria-hidden="true"
      focusable="false"
      strokeWidth={filled ? 2.35 : 1.8}
      className={cn("inline-block size-[1em] shrink-0", className)}
    />
  )
}
